---
- hosts: node1
  tasks:
  - import_tasks: tasks/general.yml

  - import_tasks: tasks/docker.yml

  - import_tasks: tasks/portainer.yml
    when: portainer_enabled == true
    tags: portainer

  - import_tasks: tasks/transmission.yml
    when: transmission_enabled == true
    tags: transmission

  - import_tasks: tasks/deluge.yml
    when: deluge_enabled == true
    tags: deluge

  - import_tasks: tasks/transmission_with_openvpn.yml
    when: transmission_with_openvpn_enabled == true
    tags: transmission

  - import_tasks: tasks/sonarr.yml
    when: sonarr_enabled == true
    tags: sonarr

  - import_tasks: tasks/radarr.yml
    when: radarr_enabled == true
    tags: radarr

  - import_tasks: tasks/glances.yml
    when: glances_enabled == true
    tags: glances

  - import_tasks: tasks/duplicati.yml
    when: duplicati_enabled == true
    tags: duplicati

  - import_tasks: tasks/couchpotato.yml
    when: couchpotato_enabled == true
    tags: couchpotato

  - import_tasks: tasks/sickrage.yml
    when: sickrage_enabled == true
    tags: sickrage

  - import_tasks: tasks/znc.yml
    when: znc_enabled == true
    tags: znc

  - import_tasks: tasks/nextcloud.yml
    when: nextcloud_enabled == true
    tags: nextcloud

  - import_tasks: tasks/stats.yml
    when: stats_enabled == true
    tags: stats

  - import_tasks: tasks/sabnzbd.yml
    when: sabnzbd_enabled == true
    tags: sabnzbd

  - import_tasks: tasks/unifi.yml
    when: unifi_enabled == true
    tags: unifi

  - import_tasks: tasks/plex.yml
    when: plex_enabled == true
    tags: plex

  - import_tasks: tasks/pihole.yml
    when: pihole_enabled == true
    tags: pihole

  - import_tasks: tasks/netatalk.yml
    when: netatalk_enabled == true
    tags: netatalk

  - import_tasks: tasks/heimdall.yml
    when: heimdall_enabled == true
    tags: heimdall

  - import_tasks: tasks/mylar.yml
    when: mylar_enabled == true
    tags: mylar

  roles:
  - { role: bertvv.samba, tags: [samba]}
  - geerlingguy.docker
