---
- name: install pip
  apt:
    name: python3-pip
    state: present

- name: 'Install docker-py'
  pip:
    name: docker-py
    state: present

- name: create docker home
  file:
    path: "{{ docker_home }}"
    mode: 0755
    state: directory

- name: add user account to docker group
  user:
    name: "{{ ansible_nas_user }}"
    group: docker
    append: yes

- name: update docker home from install default
  template:
    src: docker/daemon.json
    dest: /etc/docker/daemon.json
  register: docker_config

- name: Create docker networks
  docker_network:
    name: "{{ item.name }}"
    driver_options: 
      com.docker.network.bridge.name: "{{ item.bridge_name}}"
    ipam_options:
      subnet: "{{ item.subnet}}"
      gateway: 10.6.66.1
  with_items:
    - { name: docker_net_1, bridge_name: net1, subnet: 192.168.0.0/24 }
    - { name: docker_net_2, bridge_name: net2, subnet: 192.168.1.0/24 }
    - { name: docker_net_3, bridge_name: net3, subnet: 192.168.2.0/24 }


- name: restart docker
  service:
     name: docker
     state: restarted
  when: docker_config.changed