---

- name: Add universe repository
  apt_repository: repo="{{item}}"
  with_items:
    - "deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} universe"
    - "deb-src http://archive.ubuntu.com/ubuntu/  {{ansible_distribution_release}} universe"
    - "deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates universe"
    - "deb-src http://archive.ubuntu.com/ubuntu/  {{ansible_distribution_release}}-updates universe"

- name: Update apt-cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade all packages
  apt:
    name: "*"
    state: latest
  when: keep_packages_updated == true

- name: Install some packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - smartmontools
    - htop
    - zfsutils-linux
    - bonnie++
    - unzip
    - lm-sensors
    - avahi-daemon
    - avahi-utils

- name: Create avahi directories
  file:
    path: "/etc/avahi/services/smb.service"
    state: touch

- name: Insert/update avahi service
  blockinfile:
    path: /etc/avahi/services/smb.service
    block: |
      <?xml version="1.0" standalone='no'?>
      <!DOCTYPE service-group SYSTEM "avahi-service.dtd">
      <service-group>
      <name replace-wildcards="yes">%h</name>
      <service>
        <type>_smb._tcp</type>
        <port>445</port>
      </service>
      <service>
        <type>_device-info._tcp</type>
        <port>0</port>
        <txt-record>model=RackMac</txt-record>
      </service>
      </service-group>


- name: "Set hostname to {{ ansible_nas_hostname }}"
  hostname:
    name: "{{ ansible_nas_hostname }}"

- name: add {{ansible_nas_hostname}} to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: "127.0.0.1 localhost {{ansible_nas_hostname}}"
    state: present