---
- name: Create Plex Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ plex_config_directory }}"

- name: Create plex container
  docker_container:
    name: plex
    image: linuxserver/plex
    pull: true
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{plex_config_directory}}:/config" 
      - "{{plex_transcode_directory}}:/transcode"
      - "{{ plex_movies_directory }}:/movies:rw"
      - "{{ plex_tv_directory }}:/tv_shows:rw"
      - "{{ plex_config_directory }}:/config:rw"
      - "/etc/timezone:/etc/timezone:ro"
    hostname: plex
    env:
      PUID: "{{ plex_user_id }}"
      PGID: "{{ plex_group_id }}"
      # PLEX_CLAIM: CLAIMTOKEN
    networks:
      - name: macvlan0
        ipv4_address: "10.6.66.101"
    restart_policy: unless-stopped
    memory: 1g