---
- name: Create Unifi Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ unifi_data_directory }}"

- name: Unifi
  docker_container:
    name: unifi
    image: linuxserver/unifi:unstab
    pull: true
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ unifi_data_directory }}:/config:rw"
      - "/etc/timezone:/etc/timezone:ro"
    # ports:
    #   - "3478:3478/udp" 
    #   - "10001:10001/udp" 
    #   - "8080:8080" 
    #   - "8081:8081" 
    #   - "8443:8443" 
    #   - "8843:8843" 
    #   - "8880:8880" 
    #   - "6789:6789"   
    env:
      PUID: "{{ unifi_user_id }}"
      PGID: "{{ unifi_group_id }}"
    networks:
      - name: macvlan0
        ipv4_address: "10.6.66.102"
    restart_policy: unless-stopped
    memory: 2g