---
- name: Create Unifi Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ unfi_data_directory }}"

- name: Unfi
  docker_container:
    name: unfi
    image: linuxserver/unfi
    pull: true
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ unfi_data_directory }}:/config:rw"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - "3478:3478/udp" 
      - "10001:10001/udp" 
      - "8080:8080" 
      - "8081:8081" 
      - "8443:8443" 
      - "8843:8843" 
      - "8880:8880" 
      - "6789:6789"   
    env:
      PUID: "{{ unfi_user_id }}"
      PGID: "{{ unfi_group_id }}"
    restart_policy: unless-stopped
    memory: 1g